import React from "react";
import { Button } from "./ui/button";
import { ArrowRight, Database, MessageSquare, Sparkles, Code, Play } from "lucide-react";

const LandingPage = ({ onGetStarted, onTryDemo }) => {
  const features = [
    {
      icon: <Database className="h-6 w-6" />,
      title: "Connect Instantly",
      description: "Secure connections to PostgreSQL and MySQL databases in seconds.",
    },
    {
      icon: <MessageSquare className="h-6 w-6" />,
      title: "Natural Language",
      description: "Ask questions in plain English. Our AI understands what you need.",
    },
    {
      icon: <Code className="h-6 w-6" />,
      title: "Perfect SQL",
      description: "Get optimized, secure SQL queries generated by AIML API.",
    },
    {
      icon: <Play className="h-6 w-6" />,
      title: "Execute Safely",
      description: "Run queries with built-in security and view beautiful results.",
    },
  ];

  const examples = [
    "Show me all users who signed up last month",
    "What are the top 5 products by revenue?",
    "Find customers with more than 3 orders",
    "Show monthly sales trends for this year"
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="border-b border-border/40">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary">
                <Database className="h-4 w-4 text-primary-foreground" />
              </div>
              <span className="text-xl font-semibold">NaturalSQL</span>
            </div>
            <Button variant="outline" size="sm" onClick={onTryDemo}>
              <Sparkles className="h-4 w-4 mr-2" />
              Try Demo
            </Button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <div className="container mx-auto px-4">
        <div className="flex flex-col items-center justify-center min-h-[80vh] text-center">
          <div className="animate-fade-in">
            <div className="inline-flex items-center gap-2 bg-muted px-3 py-1 rounded-full text-sm text-muted-foreground mb-8">
              <Sparkles className="h-3 w-3" />
              Powered by AIML API
            </div>

            <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold tracking-tight mb-6">
              Ask your database
              <br />
              <span className="bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent">
                anything
              </span>
            </h1>

            <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto leading-relaxed">
              Transform natural language into SQL queries instantly. Connect your PostgreSQL or MySQL database and start getting insights in plain English.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
              <Button
                size="lg"
                onClick={onGetStarted}
                className="text-base px-8 py-6 h-auto font-medium"
              >
                Connect Your Database
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
              <Button
                variant="outline"
                size="lg"
                className="text-base px-8 py-6 h-auto font-medium"
                onClick={onTryDemo}
              >
                <Play className="mr-2 h-4 w-4" />
                Try Demo
              </Button>
            </div>
          </div>

          {/* Example Queries */}
          <div className="animate-slide-up max-w-4xl mx-auto">
            <p className="text-sm text-muted-foreground mb-4">Try asking:</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {examples.map((example, index) => (
                <div
                  key={index}
                  className="bg-card border border-border/50 rounded-lg px-4 py-3 text-sm text-card-foreground hover:border-border transition-colors cursor-pointer"
                >
                  "{example}"
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <section className="py-24 border-t border-border/40">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Everything you need
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Powerful features designed for modern data teams
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="group">
                <div className="bg-card border border-border/50 rounded-xl p-6 h-full hover:border-border transition-all duration-200">
                  <div className="mb-4">
                    <div className="inline-flex items-center justify-center w-10 h-10 bg-muted rounded-lg group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                      {feature.icon}
                    </div>
                  </div>
                  <h3 className="text-lg font-semibold mb-2">
                    {feature.title}
                  </h3>
                  <p className="text-muted-foreground text-sm leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 border-t border-border/40">
        <div className="container mx-auto px-4">
          <div className="text-center max-w-3xl mx-auto">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Ready to transform your data workflow?
            </h2>
            <p className="text-lg text-muted-foreground mb-8">
              Join thousands of developers and analysts who use NaturalSQL to query their databases with natural language.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button
                size="lg"
                onClick={onGetStarted}
                className="text-base px-8 py-6 h-auto font-medium"
              >
                Get Started Free
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
              <Button
                variant="outline"
                size="lg"
                className="text-base px-8 py-6 h-auto font-medium"
                onClick={onTryDemo}
              >
                <Play className="mr-2 h-4 w-4" />
                Try Demo
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/40 py-12">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="flex items-center gap-2 mb-4 md:mb-0">
              <div className="flex h-6 w-6 items-center justify-center rounded bg-primary">
                <Database className="h-3 w-3 text-primary-foreground" />
              </div>
              <span className="font-semibold">NaturalSQL</span>
            </div>
            <div className="flex items-center gap-6 text-sm text-muted-foreground">
              <span>Built with ❤️ for data teams</span>
              <span>•</span>
              <span>Powered by AIML API</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
